# 使用语言
language: node_js
# node版本
node_js: 6.9.4
# 设置只监听哪个分支
branches:
  only:
  - source
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  directories:
    - node_modules
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "winar-jin"
- git config --global user.email "winar1994@outlook.com"
- npm install -g hexo-cli
install:
# 不用yarn的话这里改成 npm i 即可

script:
- npm install
- hexo c
after_success:
- hexo g
- sed -i'' "/^ *repo/s~github\.com~${REPO_TOKEN}@github.com~" _config.yml
- hexo deploy -g