# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Winar  # your blog title name
subtitle: Somthing that coming to my mind~
author: 徐 进 # 作者
language: zh
timezone: 

# custom Site settings
# more detail check out docs
SEOTitle: Winar's personal blog 
header-img: //7xss68.com1.z0.glb.clouddn.com/blog/common/logo2.jpg
email: xujin94@126.com
description: "徐进在Github上的个人博客"
keyword: frontend

favicon: //7xss68.com1.z0.glb.clouddn.com/blog/common/logo.png # your favicon png
# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://xujin.pro
root: /
permalink: :year-:month-:day-:title.html
permalink_defaults:
  lang: zh

# SNS settings
# RSS:
weibo_username: winarjin
zhihu_username: xu-jin-61-91
github_username: winar-jin
twitter_username: WinarJin
facebook_username:  winar.jin
linkedin_username:  

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username: winar

# Duoshuo settings
duoshuo_username:  # 你的多说帐号
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id:
# Google Analytics
ga_track_id: UA-102177893-1 # Format: UA-xxxxxx-xx
ga_domain: xujin.pro

# Sidebar settings
sidebar-about-description: 蝉不知雪，便以为世界仅到秋。 # 个人描述
sidebar-avatar: //7xss68.com1.z0.glb.clouddn.com/blog/common/logo.png # use absolute URL


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# friends
friends:  # 友链

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

markdown:
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji

## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: https://github.com/winar-jin/winar-jin.github.io.git
  branch: master
  message: 


# img CDN path
cdn-url: 7xss68.com1.z0.glb.clouddn.com  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: //7xss68.com1.z0.glb.clouddn.com/blog/common/logo2.jpg #博文默认的图片
post-default-img-mobile: //7xss68.com1.z0.glb.clouddn.com/blog/common/logo2.jpg #移动端显示的图片

# search api , set your custom key
swiftype_key: 


# archive page title 
archive:
    title: archives
    description: 可以根据归档日期检索所有文件
